-- Словарь приёмов (активных навыков) пала: внутренний код -> русское имя.
-- waza_names.lua переводит числовой EPalWazaID -> код (напр. "Flamethrower"),
-- а этот словарь доводит его до русского. Чего нет — покажем код как есть.
-- Источник русских имён: paldb.cc/ru (подтверждено) + описательный перевод по смыслу.
-- Уникальные приёмы палов (Unique_...) в словаре нет — их у мода режется префикс
-- в main.lua (conv_waza), покажет хвост кода. Нужное имя добавляй сюда одной строкой.
return {
    -- === ОБЫЧНЫЕ (Neutral) ===
    ["EnergyShot"]      = "Энергетический выстрел",
    ["HyperBeam"]       = "Гипер-луч",
    ["PowerShot"]       = "Мощный выстрел",
    ["PowerBall"]       = "Мощный шар",
    ["Intimidate"]      = "Устрашение",
    -- базовые ближние (есть почти у каждого пала)
    ["Tackle"]          = "Таран",
    ["Roll"]            = "Перекат",
    ["ChickenPeck"]     = "Клевок",
    ["Whip"]            = "Хлыст",
    ["FlyingTackle"]    = "Летящий таран",
    ["Bite"]            = "Укус",
    ["BiteV2"]          = "Укус II",
    ["AirCanon"]        = "Воздушная пушка",
    ["AirBlade"]        = "Воздушный клинок",
    ["WindBurst"]       = "Порыв ветра",
    ["SelfDestruct"]    = "Самоуничтожение",
    ["SelfDestruct_Bee"]= "Самоуничтожение",
    ["SelfExplosion"]   = "Самоподрыв",
    ["RadiantBarrage"]  = "Сияющий залп",
    ["HolyBlast"]       = "Священный взрыв",
    ["RockBeat"]        = "Каменный бой",
    ["PredatorBeam"]    = "Луч хищника",
    ["PredatorWave"]    = "Волна хищника",
    ["PredatorLockon"]  = "Захват хищника",

    -- === ОГОНЬ === (paldb-подтв.: FireBall, FlareArrow, Inferno, FireBlast, FlameWall, FlameFunnel)
    ["FireBlast"]       = "Огненный выстрел",
    ["Flamethrower"]    = "Огнемёт",
    ["FireBall"]        = "Огненный шар",
    ["FlareArrow"]      = "Огненная стрела",
    ["FireSeed"]        = "Огненное семя",
    ["FlareTornado"]    = "Огненный вихрь",
    ["FlareTwister"]    = "Огненный смерч",
    ["Inferno"]         = "Инферно",
    ["Eruption"]        = "Извержение",
    ["FlameWall"]       = "Огненная стена",
    ["FlameFunnel"]     = "Огненная воронка",
    ["FireTrail"]       = "Огненный след",

    -- === ВОДА === (описательно, коды прозрачные)
    ["WaterGun"]        = "Водяная пушка",
    ["WaterWave"]       = "Водяная волна",
    ["HydroPump"]       = "Гидронасос",
    ["WaterBall"]       = "Водяной шар",
    ["WaterBalloon"]    = "Водяная бомба",
    ["TidalWave"]       = "Приливная волна",
    ["AquaJet"]         = "Водоструй",
    ["BubbleShot"]      = "Пузырный выстрел",
    ["BubbleShower"]    = "Пузырный душ",
    ["CreepingBubble"]  = "Ползущие пузыри",
    ["AcidRain"]        = "Кислотный дождь",
    ["SeaGush"]         = "Морской фонтан",
    ["RipTide"]         = "Отбойное течение",
    ["DiversionLaser"]  = "Отвлекающий лазер",
    ["HydroSlicer"]     = "Гидро-резак",
    ["LineGeyser"]      = "Линейный гейзер",

    -- === ТРАВА === (paldb-подтв.: WindCutter, GrassTornado, SeedMachinegun, SeedMine, CrossWind, WindEdge, RaidCutter)
    ["WindCutter"]      = "Ветряной клинок",
    ["GrassTornado"]    = "Травяной торнадо",
    ["SolarBeam"]       = "Солнечный луч",
    ["SeedMachinegun"]  = "Семенной пулемёт",
    ["SeedMine"]        = "Семенная мина",
    ["RootAttack"]      = "Атака корнями",
    ["RootLance"]       = "Корневое копьё",
    ["SpecialCutter"]   = "Особый резак",
    ["ReflectiveShuriken"] = "Отражающий сюрикен",
    ["HealingTree"]     = "Древо исцеления",
    ["CrossWind"]       = "Перекрестие ветра",
    ["WindEdge"]        = "Веер клинков",
    ["RaidCutter"]      = "Рейдовые лезвия",

    -- === ЭЛЕКТРО === (paldb-подтв.: ThunderRain, ThreeThunder, LockonLaser, LightningStrike, ThunderSpear, TriSpark, ThunderStorm)
    ["ThunderRain"]     = "Грозовой дождь",
    ["ThunderBall"]     = "Шаровая молния",
    ["LineThunder"]     = "Линейная молния",
    ["CrossThunder"]    = "Перекрёстная молния",
    ["ThreeThunder"]    = "Тройная молния",
    ["TriSpark"]        = "Тройной разряд",
    ["ElecWave"]        = "Электроволна",
    ["ElecBall"]        = "Электрошар",
    ["Thunderbolt"]     = "Удар молнии",
    ["ThunderFunnel"]   = "Грозовая воронка",
    ["SpreadPulse"]     = "Рассеянный импульс",
    ["LockonLaser"]     = "Лазерный захват",
    ["LightningStrike"] = "Грозовой удар",
    ["ThunderSpear"]    = "Грозовое копьё",
    ["ThunderStorm"]    = "Грозовая буря",
    ["RangeThunder"]    = "Вездесущая гроза",
    ["Railbolt"]        = "Цепь молний",

    -- === ЛЁД ===
    ["IceMissile"]      = "Ледяная ракета",
    ["IceBlast"]        = "Ледовзрыв",
    ["IceSpike"]        = "Ледяной шип",
    ["IceBlade"]        = "Ледяной клинок",
    ["IceWall"]         = "Ледяная стена",
    ["IceAge"]          = "Ледниковый период",
    ["BlizzardLance"]   = "Копьё метели",
    ["Blizzard"]        = "Метель",
    ["SnowStorm"]       = "Снежная буря",
    ["IcicleThrow"]     = "Бросок сосульки",
    ["IciclePierce"]    = "Прокол сосулькой",
    ["DoubleIcicleThrow"] = "Двойной бросок сосулек",
    ["IcicleLine"]      = "Ледяной след",
    ["FrostBreath"]     = "Морозное дыхание",
    ["DiamondFall"]     = "Алмазопад",

    -- === ЗЕМЛЯ === (paldb-подтв.: RockLance, MudShot, SandTornado, SandTwister)
    ["SandTornado"]     = "Песчаный вихрь",
    ["SandTwister"]     = "Песчаные смерчи",
    ["SandBlast"]       = "Песковзрыв",
    ["ThrowRock"]       = "Бросок камня",
    ["RockLance"]       = "Каменные копья",
    ["RockBlast"]       = "Камневзрыв",
    ["MudShot"]         = "Грязевой выстрел",
    ["MudSplash"]       = "Грязевой всплеск",
    ["StoneShotgun"]    = "Каменный дробовик",
    ["Spike"]           = "Шипы",
    ["Tremor"]          = "Тремор",

    -- === ТЬМА === (paldb-подтв.: DarkLaser, DarkBall, DarkCanon, DarkArrow, PoisonFog, PoisonShot, Apocalypse)
    ["DarkLaser"]       = "Тёмный лазер",
    ["DarkWave"]        = "Тёмная волна",
    ["DarkBall"]        = "Тёмный шар",
    ["DarkCanon"]       = "Тёмная пушка",
    ["DarkArrow"]       = "Стрелы тьмы",
    ["DarkPulse"]       = "Тёмный импульс",
    ["DarkLegion"]      = "Легион тьмы",
    ["ShadowBall"]      = "Теневой шар",
    ["GhostFlame"]      = "Призрачное пламя",
    ["Psychokinesis"]   = "Психокинез",
    ["GravityShot"]     = "Гравитационный выстрел",
    ["PoisonShot"]      = "Ядовитый выстрел",
    ["PoisonFog"]       = "Ядовитый туман",
    ["Apocalypse"]      = "Апокалипсис",
    ["StarMine"]        = "Звёздная мина",
    ["StardustArrow"]   = "Звёздная стрела",

    -- === ДРАКОН === (paldb-подтв.: DragonCanon, DragonBreath, DragonMeteor, BeamSlicer, BlastCanon, ChargeCanon)
    ["DragonMeteor"]    = "Драконий метеор",
    ["DragonBreath"]    = "Дыхание дракона",
    ["DragonWave"]      = "Драконья волна",
    ["DragonCanon"]     = "Драконья пушка",
    ["BeamSlicer"]      = "Режущий луч",
    ["BlastCanon"]      = "Взрывная пушка",
    ["ChargeCanon"]     = "Заряженный выстрел",
    ["ShokeiLaser"]     = "Лазерная экзекуция",
    ["Commet"]          = "Комета",
    ["ThreeCommet"]     = "Тройная комета",
    ["CommetRain"]      = "Метеоритный дождь",

    -- === уникальные (описательно, встречены в логе) ===
    ["Unique_Deer_PushupHorn"] = "Таранный рог",
}
